apiVersion: v1
kind: Service
metadata:
  labels:
    app: testlb
  name: testlb
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test
  type: LoadBalancer
status:
  loadBalancer: {}
